version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}-{{ arch }}
      - run:
          name: cache mods
          command: |
            go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}-{{ arch }}
          paths:
            - /go/pkg/mod
      - run:
          name: run tests
          command: |
            go test -v ./...

workflows:
  version: 2
  go-textile-threads:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
