// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package net_api_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	PubKey               []byte   `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Header) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetHostIDRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostIDRequest) Reset()         { *m = GetHostIDRequest{} }
func (m *GetHostIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetHostIDRequest) ProtoMessage()    {}
func (*GetHostIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *GetHostIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostIDRequest.Unmarshal(m, b)
}
func (m *GetHostIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostIDRequest.Marshal(b, m, deterministic)
}
func (m *GetHostIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostIDRequest.Merge(m, src)
}
func (m *GetHostIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetHostIDRequest.Size(m)
}
func (m *GetHostIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostIDRequest proto.InternalMessageInfo

type GetHostIDReply struct {
	PeerID               []byte   `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostIDReply) Reset()         { *m = GetHostIDReply{} }
func (m *GetHostIDReply) String() string { return proto.CompactTextString(m) }
func (*GetHostIDReply) ProtoMessage()    {}
func (*GetHostIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *GetHostIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostIDReply.Unmarshal(m, b)
}
func (m *GetHostIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostIDReply.Marshal(b, m, deterministic)
}
func (m *GetHostIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostIDReply.Merge(m, src)
}
func (m *GetHostIDReply) XXX_Size() int {
	return xxx_messageInfo_GetHostIDReply.Size(m)
}
func (m *GetHostIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostIDReply proto.InternalMessageInfo

func (m *GetHostIDReply) GetPeerID() []byte {
	if m != nil {
		return m.PeerID
	}
	return nil
}

type Keys struct {
	ThreadKey            []byte   `protobuf:"bytes,1,opt,name=threadKey,proto3" json:"threadKey,omitempty"`
	LogKey               []byte   `protobuf:"bytes,2,opt,name=logKey,proto3" json:"logKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Keys) Reset()         { *m = Keys{} }
func (m *Keys) String() string { return proto.CompactTextString(m) }
func (*Keys) ProtoMessage()    {}
func (*Keys) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Keys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keys.Unmarshal(m, b)
}
func (m *Keys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keys.Marshal(b, m, deterministic)
}
func (m *Keys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keys.Merge(m, src)
}
func (m *Keys) XXX_Size() int {
	return xxx_messageInfo_Keys.Size(m)
}
func (m *Keys) XXX_DiscardUnknown() {
	xxx_messageInfo_Keys.DiscardUnknown(m)
}

var xxx_messageInfo_Keys proto.InternalMessageInfo

func (m *Keys) GetThreadKey() []byte {
	if m != nil {
		return m.ThreadKey
	}
	return nil
}

func (m *Keys) GetLogKey() []byte {
	if m != nil {
		return m.LogKey
	}
	return nil
}

type CreateThreadRequest struct {
	Header               *Header                   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *CreateThreadRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CreateThreadRequest) Reset()         { *m = CreateThreadRequest{} }
func (m *CreateThreadRequest) String() string { return proto.CompactTextString(m) }
func (*CreateThreadRequest) ProtoMessage()    {}
func (*CreateThreadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *CreateThreadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThreadRequest.Unmarshal(m, b)
}
func (m *CreateThreadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThreadRequest.Marshal(b, m, deterministic)
}
func (m *CreateThreadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThreadRequest.Merge(m, src)
}
func (m *CreateThreadRequest) XXX_Size() int {
	return xxx_messageInfo_CreateThreadRequest.Size(m)
}
func (m *CreateThreadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThreadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThreadRequest proto.InternalMessageInfo

func (m *CreateThreadRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateThreadRequest) GetBody() *CreateThreadRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type CreateThreadRequest_Body struct {
	ThreadID             []byte   `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	Keys                 *Keys    `protobuf:"bytes,2,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateThreadRequest_Body) Reset()         { *m = CreateThreadRequest_Body{} }
func (m *CreateThreadRequest_Body) String() string { return proto.CompactTextString(m) }
func (*CreateThreadRequest_Body) ProtoMessage()    {}
func (*CreateThreadRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4, 0}
}

func (m *CreateThreadRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThreadRequest_Body.Unmarshal(m, b)
}
func (m *CreateThreadRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThreadRequest_Body.Marshal(b, m, deterministic)
}
func (m *CreateThreadRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThreadRequest_Body.Merge(m, src)
}
func (m *CreateThreadRequest_Body) XXX_Size() int {
	return xxx_messageInfo_CreateThreadRequest_Body.Size(m)
}
func (m *CreateThreadRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThreadRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThreadRequest_Body proto.InternalMessageInfo

func (m *CreateThreadRequest_Body) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

func (m *CreateThreadRequest_Body) GetKeys() *Keys {
	if m != nil {
		return m.Keys
	}
	return nil
}

type LogInfo struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	PrivKey              []byte   `protobuf:"bytes,3,opt,name=privKey,proto3" json:"privKey,omitempty"`
	Addrs                [][]byte `protobuf:"bytes,4,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Head                 []byte   `protobuf:"bytes,5,opt,name=head,proto3" json:"head,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInfo) Reset()         { *m = LogInfo{} }
func (m *LogInfo) String() string { return proto.CompactTextString(m) }
func (*LogInfo) ProtoMessage()    {}
func (*LogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *LogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInfo.Unmarshal(m, b)
}
func (m *LogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInfo.Marshal(b, m, deterministic)
}
func (m *LogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInfo.Merge(m, src)
}
func (m *LogInfo) XXX_Size() int {
	return xxx_messageInfo_LogInfo.Size(m)
}
func (m *LogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LogInfo proto.InternalMessageInfo

func (m *LogInfo) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *LogInfo) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *LogInfo) GetPrivKey() []byte {
	if m != nil {
		return m.PrivKey
	}
	return nil
}

func (m *LogInfo) GetAddrs() [][]byte {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *LogInfo) GetHead() []byte {
	if m != nil {
		return m.Head
	}
	return nil
}

type ThreadInfoReply struct {
	ThreadID             []byte     `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	ThreadKey            []byte     `protobuf:"bytes,2,opt,name=threadKey,proto3" json:"threadKey,omitempty"`
	Logs                 []*LogInfo `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ThreadInfoReply) Reset()         { *m = ThreadInfoReply{} }
func (m *ThreadInfoReply) String() string { return proto.CompactTextString(m) }
func (*ThreadInfoReply) ProtoMessage()    {}
func (*ThreadInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *ThreadInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadInfoReply.Unmarshal(m, b)
}
func (m *ThreadInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadInfoReply.Marshal(b, m, deterministic)
}
func (m *ThreadInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadInfoReply.Merge(m, src)
}
func (m *ThreadInfoReply) XXX_Size() int {
	return xxx_messageInfo_ThreadInfoReply.Size(m)
}
func (m *ThreadInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadInfoReply proto.InternalMessageInfo

func (m *ThreadInfoReply) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

func (m *ThreadInfoReply) GetThreadKey() []byte {
	if m != nil {
		return m.ThreadKey
	}
	return nil
}

func (m *ThreadInfoReply) GetLogs() []*LogInfo {
	if m != nil {
		return m.Logs
	}
	return nil
}

type AddThreadRequest struct {
	Header               *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *AddThreadRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AddThreadRequest) Reset()         { *m = AddThreadRequest{} }
func (m *AddThreadRequest) String() string { return proto.CompactTextString(m) }
func (*AddThreadRequest) ProtoMessage()    {}
func (*AddThreadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *AddThreadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddThreadRequest.Unmarshal(m, b)
}
func (m *AddThreadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddThreadRequest.Marshal(b, m, deterministic)
}
func (m *AddThreadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddThreadRequest.Merge(m, src)
}
func (m *AddThreadRequest) XXX_Size() int {
	return xxx_messageInfo_AddThreadRequest.Size(m)
}
func (m *AddThreadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddThreadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddThreadRequest proto.InternalMessageInfo

func (m *AddThreadRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AddThreadRequest) GetBody() *AddThreadRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type AddThreadRequest_Body struct {
	Addr                 []byte   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Keys                 *Keys    `protobuf:"bytes,2,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddThreadRequest_Body) Reset()         { *m = AddThreadRequest_Body{} }
func (m *AddThreadRequest_Body) String() string { return proto.CompactTextString(m) }
func (*AddThreadRequest_Body) ProtoMessage()    {}
func (*AddThreadRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7, 0}
}

func (m *AddThreadRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddThreadRequest_Body.Unmarshal(m, b)
}
func (m *AddThreadRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddThreadRequest_Body.Marshal(b, m, deterministic)
}
func (m *AddThreadRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddThreadRequest_Body.Merge(m, src)
}
func (m *AddThreadRequest_Body) XXX_Size() int {
	return xxx_messageInfo_AddThreadRequest_Body.Size(m)
}
func (m *AddThreadRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_AddThreadRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_AddThreadRequest_Body proto.InternalMessageInfo

func (m *AddThreadRequest_Body) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *AddThreadRequest_Body) GetKeys() *Keys {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetThreadRequest struct {
	Header               *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *GetThreadRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetThreadRequest) Reset()         { *m = GetThreadRequest{} }
func (m *GetThreadRequest) String() string { return proto.CompactTextString(m) }
func (*GetThreadRequest) ProtoMessage()    {}
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *GetThreadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThreadRequest.Unmarshal(m, b)
}
func (m *GetThreadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThreadRequest.Marshal(b, m, deterministic)
}
func (m *GetThreadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThreadRequest.Merge(m, src)
}
func (m *GetThreadRequest) XXX_Size() int {
	return xxx_messageInfo_GetThreadRequest.Size(m)
}
func (m *GetThreadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThreadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetThreadRequest proto.InternalMessageInfo

func (m *GetThreadRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetThreadRequest) GetBody() *GetThreadRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type GetThreadRequest_Body struct {
	ThreadID             []byte   `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThreadRequest_Body) Reset()         { *m = GetThreadRequest_Body{} }
func (m *GetThreadRequest_Body) String() string { return proto.CompactTextString(m) }
func (*GetThreadRequest_Body) ProtoMessage()    {}
func (*GetThreadRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8, 0}
}

func (m *GetThreadRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThreadRequest_Body.Unmarshal(m, b)
}
func (m *GetThreadRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThreadRequest_Body.Marshal(b, m, deterministic)
}
func (m *GetThreadRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThreadRequest_Body.Merge(m, src)
}
func (m *GetThreadRequest_Body) XXX_Size() int {
	return xxx_messageInfo_GetThreadRequest_Body.Size(m)
}
func (m *GetThreadRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThreadRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetThreadRequest_Body proto.InternalMessageInfo

func (m *GetThreadRequest_Body) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

type PullThreadRequest struct {
	Header               *Header                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *PullThreadRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PullThreadRequest) Reset()         { *m = PullThreadRequest{} }
func (m *PullThreadRequest) String() string { return proto.CompactTextString(m) }
func (*PullThreadRequest) ProtoMessage()    {}
func (*PullThreadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *PullThreadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullThreadRequest.Unmarshal(m, b)
}
func (m *PullThreadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullThreadRequest.Marshal(b, m, deterministic)
}
func (m *PullThreadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullThreadRequest.Merge(m, src)
}
func (m *PullThreadRequest) XXX_Size() int {
	return xxx_messageInfo_PullThreadRequest.Size(m)
}
func (m *PullThreadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullThreadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullThreadRequest proto.InternalMessageInfo

func (m *PullThreadRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PullThreadRequest) GetBody() *PullThreadRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type PullThreadRequest_Body struct {
	ThreadID             []byte   `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullThreadRequest_Body) Reset()         { *m = PullThreadRequest_Body{} }
func (m *PullThreadRequest_Body) String() string { return proto.CompactTextString(m) }
func (*PullThreadRequest_Body) ProtoMessage()    {}
func (*PullThreadRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9, 0}
}

func (m *PullThreadRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullThreadRequest_Body.Unmarshal(m, b)
}
func (m *PullThreadRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullThreadRequest_Body.Marshal(b, m, deterministic)
}
func (m *PullThreadRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullThreadRequest_Body.Merge(m, src)
}
func (m *PullThreadRequest_Body) XXX_Size() int {
	return xxx_messageInfo_PullThreadRequest_Body.Size(m)
}
func (m *PullThreadRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_PullThreadRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_PullThreadRequest_Body proto.InternalMessageInfo

func (m *PullThreadRequest_Body) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

type PullThreadReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullThreadReply) Reset()         { *m = PullThreadReply{} }
func (m *PullThreadReply) String() string { return proto.CompactTextString(m) }
func (*PullThreadReply) ProtoMessage()    {}
func (*PullThreadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *PullThreadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullThreadReply.Unmarshal(m, b)
}
func (m *PullThreadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullThreadReply.Marshal(b, m, deterministic)
}
func (m *PullThreadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullThreadReply.Merge(m, src)
}
func (m *PullThreadReply) XXX_Size() int {
	return xxx_messageInfo_PullThreadReply.Size(m)
}
func (m *PullThreadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PullThreadReply.DiscardUnknown(m)
}

var xxx_messageInfo_PullThreadReply proto.InternalMessageInfo

type DeleteThreadRequest struct {
	Header               *Header                   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *DeleteThreadRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DeleteThreadRequest) Reset()         { *m = DeleteThreadRequest{} }
func (m *DeleteThreadRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteThreadRequest) ProtoMessage()    {}
func (*DeleteThreadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *DeleteThreadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteThreadRequest.Unmarshal(m, b)
}
func (m *DeleteThreadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteThreadRequest.Marshal(b, m, deterministic)
}
func (m *DeleteThreadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteThreadRequest.Merge(m, src)
}
func (m *DeleteThreadRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteThreadRequest.Size(m)
}
func (m *DeleteThreadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteThreadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteThreadRequest proto.InternalMessageInfo

func (m *DeleteThreadRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DeleteThreadRequest) GetBody() *DeleteThreadRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type DeleteThreadRequest_Body struct {
	ThreadID             []byte   `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteThreadRequest_Body) Reset()         { *m = DeleteThreadRequest_Body{} }
func (m *DeleteThreadRequest_Body) String() string { return proto.CompactTextString(m) }
func (*DeleteThreadRequest_Body) ProtoMessage()    {}
func (*DeleteThreadRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11, 0}
}

func (m *DeleteThreadRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteThreadRequest_Body.Unmarshal(m, b)
}
func (m *DeleteThreadRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteThreadRequest_Body.Marshal(b, m, deterministic)
}
func (m *DeleteThreadRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteThreadRequest_Body.Merge(m, src)
}
func (m *DeleteThreadRequest_Body) XXX_Size() int {
	return xxx_messageInfo_DeleteThreadRequest_Body.Size(m)
}
func (m *DeleteThreadRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteThreadRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteThreadRequest_Body proto.InternalMessageInfo

func (m *DeleteThreadRequest_Body) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

type DeleteThreadReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteThreadReply) Reset()         { *m = DeleteThreadReply{} }
func (m *DeleteThreadReply) String() string { return proto.CompactTextString(m) }
func (*DeleteThreadReply) ProtoMessage()    {}
func (*DeleteThreadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *DeleteThreadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteThreadReply.Unmarshal(m, b)
}
func (m *DeleteThreadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteThreadReply.Marshal(b, m, deterministic)
}
func (m *DeleteThreadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteThreadReply.Merge(m, src)
}
func (m *DeleteThreadReply) XXX_Size() int {
	return xxx_messageInfo_DeleteThreadReply.Size(m)
}
func (m *DeleteThreadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteThreadReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteThreadReply proto.InternalMessageInfo

type AddReplicatorRequest struct {
	Header               *Header                    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *AddReplicatorRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AddReplicatorRequest) Reset()         { *m = AddReplicatorRequest{} }
func (m *AddReplicatorRequest) String() string { return proto.CompactTextString(m) }
func (*AddReplicatorRequest) ProtoMessage()    {}
func (*AddReplicatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *AddReplicatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReplicatorRequest.Unmarshal(m, b)
}
func (m *AddReplicatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReplicatorRequest.Marshal(b, m, deterministic)
}
func (m *AddReplicatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReplicatorRequest.Merge(m, src)
}
func (m *AddReplicatorRequest) XXX_Size() int {
	return xxx_messageInfo_AddReplicatorRequest.Size(m)
}
func (m *AddReplicatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReplicatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddReplicatorRequest proto.InternalMessageInfo

func (m *AddReplicatorRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AddReplicatorRequest) GetBody() *AddReplicatorRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type AddReplicatorRequest_Body struct {
	ThreadID             []byte   `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	Addr                 []byte   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReplicatorRequest_Body) Reset()         { *m = AddReplicatorRequest_Body{} }
func (m *AddReplicatorRequest_Body) String() string { return proto.CompactTextString(m) }
func (*AddReplicatorRequest_Body) ProtoMessage()    {}
func (*AddReplicatorRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13, 0}
}

func (m *AddReplicatorRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReplicatorRequest_Body.Unmarshal(m, b)
}
func (m *AddReplicatorRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReplicatorRequest_Body.Marshal(b, m, deterministic)
}
func (m *AddReplicatorRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReplicatorRequest_Body.Merge(m, src)
}
func (m *AddReplicatorRequest_Body) XXX_Size() int {
	return xxx_messageInfo_AddReplicatorRequest_Body.Size(m)
}
func (m *AddReplicatorRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReplicatorRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_AddReplicatorRequest_Body proto.InternalMessageInfo

func (m *AddReplicatorRequest_Body) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

func (m *AddReplicatorRequest_Body) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

type AddReplicatorReply struct {
	PeerID               []byte   `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReplicatorReply) Reset()         { *m = AddReplicatorReply{} }
func (m *AddReplicatorReply) String() string { return proto.CompactTextString(m) }
func (*AddReplicatorReply) ProtoMessage()    {}
func (*AddReplicatorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *AddReplicatorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReplicatorReply.Unmarshal(m, b)
}
func (m *AddReplicatorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReplicatorReply.Marshal(b, m, deterministic)
}
func (m *AddReplicatorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReplicatorReply.Merge(m, src)
}
func (m *AddReplicatorReply) XXX_Size() int {
	return xxx_messageInfo_AddReplicatorReply.Size(m)
}
func (m *AddReplicatorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReplicatorReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddReplicatorReply proto.InternalMessageInfo

func (m *AddReplicatorReply) GetPeerID() []byte {
	if m != nil {
		return m.PeerID
	}
	return nil
}

type CreateRecordRequest struct {
	Header               *Header                   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *CreateRecordRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CreateRecordRequest) Reset()         { *m = CreateRecordRequest{} }
func (m *CreateRecordRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecordRequest) ProtoMessage()    {}
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *CreateRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecordRequest.Unmarshal(m, b)
}
func (m *CreateRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecordRequest.Marshal(b, m, deterministic)
}
func (m *CreateRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecordRequest.Merge(m, src)
}
func (m *CreateRecordRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecordRequest.Size(m)
}
func (m *CreateRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecordRequest proto.InternalMessageInfo

func (m *CreateRecordRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateRecordRequest) GetBody() *CreateRecordRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type CreateRecordRequest_Body struct {
	ThreadID             []byte   `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecordRequest_Body) Reset()         { *m = CreateRecordRequest_Body{} }
func (m *CreateRecordRequest_Body) String() string { return proto.CompactTextString(m) }
func (*CreateRecordRequest_Body) ProtoMessage()    {}
func (*CreateRecordRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15, 0}
}

func (m *CreateRecordRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecordRequest_Body.Unmarshal(m, b)
}
func (m *CreateRecordRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecordRequest_Body.Marshal(b, m, deterministic)
}
func (m *CreateRecordRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecordRequest_Body.Merge(m, src)
}
func (m *CreateRecordRequest_Body) XXX_Size() int {
	return xxx_messageInfo_CreateRecordRequest_Body.Size(m)
}
func (m *CreateRecordRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecordRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecordRequest_Body proto.InternalMessageInfo

func (m *CreateRecordRequest_Body) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

func (m *CreateRecordRequest_Body) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Record struct {
	RecordNode           []byte   `protobuf:"bytes,1,opt,name=recordNode,proto3" json:"recordNode,omitempty"`
	EventNode            []byte   `protobuf:"bytes,2,opt,name=eventNode,proto3" json:"eventNode,omitempty"`
	HeaderNode           []byte   `protobuf:"bytes,3,opt,name=headerNode,proto3" json:"headerNode,omitempty"`
	BodyNode             []byte   `protobuf:"bytes,4,opt,name=bodyNode,proto3" json:"bodyNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetRecordNode() []byte {
	if m != nil {
		return m.RecordNode
	}
	return nil
}

func (m *Record) GetEventNode() []byte {
	if m != nil {
		return m.EventNode
	}
	return nil
}

func (m *Record) GetHeaderNode() []byte {
	if m != nil {
		return m.HeaderNode
	}
	return nil
}

func (m *Record) GetBodyNode() []byte {
	if m != nil {
		return m.BodyNode
	}
	return nil
}

type NewRecordReply struct {
	ThreadID             []byte   `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	LogID                []byte   `protobuf:"bytes,2,opt,name=logID,proto3" json:"logID,omitempty"`
	Record               *Record  `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRecordReply) Reset()         { *m = NewRecordReply{} }
func (m *NewRecordReply) String() string { return proto.CompactTextString(m) }
func (*NewRecordReply) ProtoMessage()    {}
func (*NewRecordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *NewRecordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRecordReply.Unmarshal(m, b)
}
func (m *NewRecordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRecordReply.Marshal(b, m, deterministic)
}
func (m *NewRecordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRecordReply.Merge(m, src)
}
func (m *NewRecordReply) XXX_Size() int {
	return xxx_messageInfo_NewRecordReply.Size(m)
}
func (m *NewRecordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRecordReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewRecordReply proto.InternalMessageInfo

func (m *NewRecordReply) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

func (m *NewRecordReply) GetLogID() []byte {
	if m != nil {
		return m.LogID
	}
	return nil
}

func (m *NewRecordReply) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type AddRecordRequest struct {
	Header               *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *AddRecordRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AddRecordRequest) Reset()         { *m = AddRecordRequest{} }
func (m *AddRecordRequest) String() string { return proto.CompactTextString(m) }
func (*AddRecordRequest) ProtoMessage()    {}
func (*AddRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *AddRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecordRequest.Unmarshal(m, b)
}
func (m *AddRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecordRequest.Marshal(b, m, deterministic)
}
func (m *AddRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecordRequest.Merge(m, src)
}
func (m *AddRecordRequest) XXX_Size() int {
	return xxx_messageInfo_AddRecordRequest.Size(m)
}
func (m *AddRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecordRequest proto.InternalMessageInfo

func (m *AddRecordRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AddRecordRequest) GetBody() *AddRecordRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type AddRecordRequest_Body struct {
	ThreadID             []byte   `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	LogID                []byte   `protobuf:"bytes,2,opt,name=logID,proto3" json:"logID,omitempty"`
	Record               *Record  `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRecordRequest_Body) Reset()         { *m = AddRecordRequest_Body{} }
func (m *AddRecordRequest_Body) String() string { return proto.CompactTextString(m) }
func (*AddRecordRequest_Body) ProtoMessage()    {}
func (*AddRecordRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18, 0}
}

func (m *AddRecordRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecordRequest_Body.Unmarshal(m, b)
}
func (m *AddRecordRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecordRequest_Body.Marshal(b, m, deterministic)
}
func (m *AddRecordRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecordRequest_Body.Merge(m, src)
}
func (m *AddRecordRequest_Body) XXX_Size() int {
	return xxx_messageInfo_AddRecordRequest_Body.Size(m)
}
func (m *AddRecordRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecordRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecordRequest_Body proto.InternalMessageInfo

func (m *AddRecordRequest_Body) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

func (m *AddRecordRequest_Body) GetLogID() []byte {
	if m != nil {
		return m.LogID
	}
	return nil
}

func (m *AddRecordRequest_Body) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type AddRecordReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRecordReply) Reset()         { *m = AddRecordReply{} }
func (m *AddRecordReply) String() string { return proto.CompactTextString(m) }
func (*AddRecordReply) ProtoMessage()    {}
func (*AddRecordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *AddRecordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecordReply.Unmarshal(m, b)
}
func (m *AddRecordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecordReply.Marshal(b, m, deterministic)
}
func (m *AddRecordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecordReply.Merge(m, src)
}
func (m *AddRecordReply) XXX_Size() int {
	return xxx_messageInfo_AddRecordReply.Size(m)
}
func (m *AddRecordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecordReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecordReply proto.InternalMessageInfo

type GetRecordRequest struct {
	Header               *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *GetRecordRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetRecordRequest) Reset()         { *m = GetRecordRequest{} }
func (m *GetRecordRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordRequest) ProtoMessage()    {}
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *GetRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordRequest.Unmarshal(m, b)
}
func (m *GetRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordRequest.Merge(m, src)
}
func (m *GetRecordRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordRequest.Size(m)
}
func (m *GetRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordRequest proto.InternalMessageInfo

func (m *GetRecordRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRecordRequest) GetBody() *GetRecordRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type GetRecordRequest_Body struct {
	ThreadID             []byte   `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	RecordID             []byte   `protobuf:"bytes,2,opt,name=recordID,proto3" json:"recordID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordRequest_Body) Reset()         { *m = GetRecordRequest_Body{} }
func (m *GetRecordRequest_Body) String() string { return proto.CompactTextString(m) }
func (*GetRecordRequest_Body) ProtoMessage()    {}
func (*GetRecordRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20, 0}
}

func (m *GetRecordRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordRequest_Body.Unmarshal(m, b)
}
func (m *GetRecordRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordRequest_Body.Marshal(b, m, deterministic)
}
func (m *GetRecordRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordRequest_Body.Merge(m, src)
}
func (m *GetRecordRequest_Body) XXX_Size() int {
	return xxx_messageInfo_GetRecordRequest_Body.Size(m)
}
func (m *GetRecordRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordRequest_Body proto.InternalMessageInfo

func (m *GetRecordRequest_Body) GetThreadID() []byte {
	if m != nil {
		return m.ThreadID
	}
	return nil
}

func (m *GetRecordRequest_Body) GetRecordID() []byte {
	if m != nil {
		return m.RecordID
	}
	return nil
}

type GetRecordReply struct {
	Record               *Record  `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordReply) Reset()         { *m = GetRecordReply{} }
func (m *GetRecordReply) String() string { return proto.CompactTextString(m) }
func (*GetRecordReply) ProtoMessage()    {}
func (*GetRecordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *GetRecordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordReply.Unmarshal(m, b)
}
func (m *GetRecordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordReply.Marshal(b, m, deterministic)
}
func (m *GetRecordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordReply.Merge(m, src)
}
func (m *GetRecordReply) XXX_Size() int {
	return xxx_messageInfo_GetRecordReply.Size(m)
}
func (m *GetRecordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordReply proto.InternalMessageInfo

func (m *GetRecordReply) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type SubscribeRequest struct {
	Header               *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *SubscribeRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SubscribeRequest) GetBody() *SubscribeRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type SubscribeRequest_Body struct {
	ThreadIDs            [][]byte `protobuf:"bytes,1,rep,name=threadIDs,proto3" json:"threadIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest_Body) Reset()         { *m = SubscribeRequest_Body{} }
func (m *SubscribeRequest_Body) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest_Body) ProtoMessage()    {}
func (*SubscribeRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22, 0}
}

func (m *SubscribeRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest_Body.Unmarshal(m, b)
}
func (m *SubscribeRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest_Body.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest_Body.Merge(m, src)
}
func (m *SubscribeRequest_Body) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest_Body.Size(m)
}
func (m *SubscribeRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest_Body proto.InternalMessageInfo

func (m *SubscribeRequest_Body) GetThreadIDs() [][]byte {
	if m != nil {
		return m.ThreadIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "net.api.pb.Header")
	proto.RegisterType((*GetHostIDRequest)(nil), "net.api.pb.GetHostIDRequest")
	proto.RegisterType((*GetHostIDReply)(nil), "net.api.pb.GetHostIDReply")
	proto.RegisterType((*Keys)(nil), "net.api.pb.Keys")
	proto.RegisterType((*CreateThreadRequest)(nil), "net.api.pb.CreateThreadRequest")
	proto.RegisterType((*CreateThreadRequest_Body)(nil), "net.api.pb.CreateThreadRequest.Body")
	proto.RegisterType((*LogInfo)(nil), "net.api.pb.LogInfo")
	proto.RegisterType((*ThreadInfoReply)(nil), "net.api.pb.ThreadInfoReply")
	proto.RegisterType((*AddThreadRequest)(nil), "net.api.pb.AddThreadRequest")
	proto.RegisterType((*AddThreadRequest_Body)(nil), "net.api.pb.AddThreadRequest.Body")
	proto.RegisterType((*GetThreadRequest)(nil), "net.api.pb.GetThreadRequest")
	proto.RegisterType((*GetThreadRequest_Body)(nil), "net.api.pb.GetThreadRequest.Body")
	proto.RegisterType((*PullThreadRequest)(nil), "net.api.pb.PullThreadRequest")
	proto.RegisterType((*PullThreadRequest_Body)(nil), "net.api.pb.PullThreadRequest.Body")
	proto.RegisterType((*PullThreadReply)(nil), "net.api.pb.PullThreadReply")
	proto.RegisterType((*DeleteThreadRequest)(nil), "net.api.pb.DeleteThreadRequest")
	proto.RegisterType((*DeleteThreadRequest_Body)(nil), "net.api.pb.DeleteThreadRequest.Body")
	proto.RegisterType((*DeleteThreadReply)(nil), "net.api.pb.DeleteThreadReply")
	proto.RegisterType((*AddReplicatorRequest)(nil), "net.api.pb.AddReplicatorRequest")
	proto.RegisterType((*AddReplicatorRequest_Body)(nil), "net.api.pb.AddReplicatorRequest.Body")
	proto.RegisterType((*AddReplicatorReply)(nil), "net.api.pb.AddReplicatorReply")
	proto.RegisterType((*CreateRecordRequest)(nil), "net.api.pb.CreateRecordRequest")
	proto.RegisterType((*CreateRecordRequest_Body)(nil), "net.api.pb.CreateRecordRequest.Body")
	proto.RegisterType((*Record)(nil), "net.api.pb.Record")
	proto.RegisterType((*NewRecordReply)(nil), "net.api.pb.NewRecordReply")
	proto.RegisterType((*AddRecordRequest)(nil), "net.api.pb.AddRecordRequest")
	proto.RegisterType((*AddRecordRequest_Body)(nil), "net.api.pb.AddRecordRequest.Body")
	proto.RegisterType((*AddRecordReply)(nil), "net.api.pb.AddRecordReply")
	proto.RegisterType((*GetRecordRequest)(nil), "net.api.pb.GetRecordRequest")
	proto.RegisterType((*GetRecordRequest_Body)(nil), "net.api.pb.GetRecordRequest.Body")
	proto.RegisterType((*GetRecordReply)(nil), "net.api.pb.GetRecordReply")
	proto.RegisterType((*SubscribeRequest)(nil), "net.api.pb.SubscribeRequest")
	proto.RegisterType((*SubscribeRequest_Body)(nil), "net.api.pb.SubscribeRequest.Body")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 913 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0xe2, 0x46,
	0x14, 0xc6, 0xe0, 0x90, 0x70, 0x42, 0x09, 0x19, 0xa2, 0x0a, 0x39, 0x7f, 0x74, 0x94, 0xaa, 0xa8,
	0xaa, 0x50, 0x45, 0xd5, 0x28, 0x95, 0xa2, 0xa8, 0xa4, 0x44, 0xc1, 0x4d, 0x8b, 0x90, 0x93, 0xfb,
	0x08, 0xf0, 0x94, 0xa0, 0x5a, 0x98, 0xda, 0x26, 0x2d, 0xb7, 0x7d, 0x8b, 0x2a, 0x17, 0x95, 0xf6,
	0x15, 0x56, 0xab, 0x7d, 0x82, 0x7d, 0x80, 0xbd, 0xde, 0x97, 0x59, 0xcd, 0x0f, 0xf6, 0x8c, 0x21,
	0x40, 0xd8, 0xe5, 0x8e, 0x33, 0x73, 0xfc, 0xcd, 0xf7, 0xcd, 0x39, 0x73, 0xce, 0x01, 0x32, 0xed,
	0x61, 0xbf, 0x32, 0xf4, 0xdc, 0xc0, 0x45, 0x30, 0x20, 0x41, 0x85, 0x99, 0x1d, 0x7c, 0x01, 0xe9,
	0x06, 0x69, 0xdb, 0xc4, 0x43, 0x5f, 0x42, 0x7a, 0x38, 0xea, 0xdc, 0x90, 0x71, 0x51, 0x2b, 0x69,
	0xe5, 0xac, 0x25, 0x2c, 0x74, 0x00, 0x19, 0xbf, 0xdf, 0x1b, 0xb4, 0x83, 0x91, 0x47, 0x8a, 0x49,
	0xb6, 0x15, 0x2d, 0x60, 0x04, 0xf9, 0x6b, 0x12, 0x34, 0x5c, 0x3f, 0x30, 0xeb, 0x16, 0xf9, 0x6b,
	0x44, 0xfc, 0x00, 0x97, 0x21, 0x27, 0xad, 0x0d, 0x9d, 0x31, 0xc3, 0x26, 0xc4, 0x33, 0xeb, 0x21,
	0x36, 0xb3, 0xf0, 0x39, 0xe8, 0x37, 0x64, 0xec, 0xd3, 0x33, 0x82, 0x07, 0x8f, 0xb4, 0xed, 0xe8,
	0xf8, 0x68, 0x81, 0x7e, 0xed, 0xb8, 0x3d, 0xba, 0xc5, 0x8f, 0x17, 0x16, 0x7e, 0xa7, 0x41, 0xe1,
	0x17, 0x8f, 0xb4, 0x03, 0x72, 0xc7, 0x7c, 0xc5, 0xf9, 0xe8, 0x5b, 0x48, 0x3f, 0x30, 0x4d, 0x0c,
	0x6a, 0xbb, 0x8a, 0x2a, 0x91, 0xe0, 0x0a, 0x57, 0x6b, 0x09, 0x0f, 0x74, 0x06, 0x7a, 0xc7, 0xb5,
	0x39, 0xf2, 0x76, 0xf5, 0x44, 0xf6, 0x9c, 0x01, 0x5d, 0xb9, 0x74, 0xed, 0xb1, 0xc5, 0xbe, 0x30,
	0x1a, 0xa0, 0x53, 0x0b, 0x19, 0xb0, 0xc5, 0xa9, 0x86, 0xea, 0x42, 0x1b, 0x9d, 0x80, 0xfe, 0x27,
	0x19, 0xfb, 0x02, 0x3d, 0x2f, 0xa3, 0x53, 0xdd, 0x16, 0xdb, 0xc5, 0x23, 0xd8, 0xfc, 0xcd, 0xed,
	0x99, 0x83, 0x3f, 0x5c, 0x94, 0x83, 0x64, 0x08, 0x93, 0x34, 0xeb, 0x52, 0x50, 0x92, 0x4a, 0x50,
	0x8a, 0xb0, 0x39, 0xf4, 0xfa, 0x8f, 0x74, 0x23, 0xc5, 0x36, 0x26, 0x26, 0xda, 0x83, 0x8d, 0xb6,
	0x6d, 0x7b, 0x7e, 0x51, 0x2f, 0xa5, 0xca, 0x59, 0x8b, 0x1b, 0x08, 0x81, 0x4e, 0x05, 0x17, 0x37,
	0x98, 0x33, 0xfb, 0x8d, 0x03, 0xd8, 0xe1, 0xe2, 0xe8, 0xc9, 0x3c, 0x4e, 0xf3, 0xb4, 0x28, 0x31,
	0x4a, 0xc6, 0x63, 0xf4, 0x0d, 0xe8, 0x8e, 0xdb, 0xf3, 0x8b, 0xa9, 0x52, 0xaa, 0xbc, 0x5d, 0x2d,
	0xc8, 0x4a, 0x85, 0x36, 0x8b, 0x39, 0xe0, 0xb7, 0x1a, 0xe4, 0x6b, 0xb6, 0xbd, 0x7a, 0xc4, 0x7e,
	0x54, 0x22, 0xf6, 0x95, 0xec, 0x19, 0xc7, 0x95, 0xc3, 0xf5, 0xb3, 0x08, 0x17, 0x02, 0x9d, 0x5e,
	0x89, 0x90, 0xc7, 0x7e, 0x2f, 0x19, 0xa6, 0xff, 0x34, 0x96, 0xeb, 0x6b, 0x61, 0x1e, 0xc7, 0x95,
	0x99, 0xe3, 0xc5, 0x89, 0x86, 0x9f, 0x34, 0xd8, 0x6d, 0x8d, 0x1c, 0x67, 0x75, 0x72, 0xa7, 0x0a,
	0x39, 0x2c, 0x7b, 0x4e, 0x01, 0xbf, 0x94, 0xdd, 0x2e, 0xec, 0xc8, 0x18, 0x43, 0x67, 0x8c, 0xff,
	0xd7, 0xa0, 0x50, 0x27, 0x0e, 0x59, 0xd3, 0xdb, 0x9d, 0x01, 0xfd, 0x52, 0xd2, 0x05, 0xd8, 0x55,
	0x51, 0x28, 0xed, 0x37, 0x1a, 0xec, 0xd5, 0x6c, 0x66, 0xf4, 0xbb, 0xed, 0xc0, 0xf5, 0x56, 0xe1,
	0xfd, 0x93, 0xc2, 0xfb, 0xeb, 0x58, 0x06, 0x4f, 0x61, 0xcb, 0xc4, 0x4f, 0x97, 0x28, 0x3a, 0x93,
	0x0c, 0x4f, 0x46, 0x19, 0x8e, 0xbf, 0x03, 0x14, 0x83, 0x9e, 0x57, 0x96, 0x5f, 0x87, 0x85, 0xd5,
	0x22, 0x5d, 0xd7, 0x5b, 0x4f, 0x61, 0x55, 0xa0, 0x57, 0xd0, 0x18, 0xa2, 0x67, 0xf9, 0x77, 0xf8,
	0x5f, 0x0d, 0xd2, 0x1c, 0x14, 0x1d, 0x01, 0x78, 0xec, 0x57, 0xd3, 0xb5, 0x89, 0xf8, 0x58, 0x5a,
	0xa1, 0xb5, 0x8c, 0x3c, 0x92, 0x41, 0xc0, 0xb6, 0x45, 0x2d, 0x0b, 0x17, 0xe8, 0xd7, 0x5c, 0x04,
	0xdb, 0xe6, 0xf5, 0x55, 0x5a, 0xa1, 0xc4, 0xe8, 0x81, 0x6c, 0x57, 0xe7, 0xc4, 0x26, 0x36, 0x1e,
	0x40, 0xae, 0x49, 0xfe, 0x9e, 0x68, 0x5b, 0x54, 0x53, 0xf7, 0x60, 0xc3, 0x71, 0x7b, 0x66, 0x5d,
	0x70, 0xe0, 0x06, 0xbd, 0x66, 0xce, 0x95, 0x9d, 0x1d, 0xbb, 0x66, 0x01, 0x2d, 0x3c, 0xf0, 0x07,
	0x5e, 0x4e, 0x57, 0x8f, 0xd3, 0xfc, 0x72, 0xfa, 0x6c, 0x90, 0xec, 0x25, 0x82, 0xf4, 0xe9, 0xea,
	0xf2, 0x90, 0x93, 0x48, 0x88, 0x07, 0x48, 0x8b, 0xf0, 0x5a, 0xf4, 0xc6, 0x71, 0x65, 0xbd, 0x17,
	0x4b, 0xe8, 0x35, 0x60, 0x8b, 0xf3, 0x0e, 0x25, 0x87, 0x36, 0x3e, 0x67, 0x33, 0x91, 0x9c, 0x17,
	0xd1, 0x3d, 0x68, 0x0b, 0xef, 0xe1, 0x49, 0x83, 0xfc, 0xed, 0xa8, 0xe3, 0x77, 0xbd, 0x7e, 0x87,
	0x7c, 0x66, 0xd5, 0x71, 0x5c, 0x59, 0xf5, 0x89, 0x50, 0x1d, 0xf6, 0x7e, 0xb3, 0xee, 0x17, 0x35,
	0x36, 0x58, 0x44, 0x0b, 0xd5, 0xf7, 0x69, 0x48, 0xd5, 0x5a, 0x26, 0xba, 0x86, 0x4c, 0x38, 0xf7,
	0xa1, 0x83, 0xd8, 0xcd, 0x2a, 0x23, 0xa2, 0x61, 0x3c, 0xb3, 0x4b, 0x43, 0x9c, 0x40, 0x4d, 0xc8,
	0xca, 0xc3, 0x17, 0x3a, 0x5e, 0x30, 0x96, 0x19, 0xfb, 0xb2, 0x43, 0x6c, 0xa8, 0xc1, 0x09, 0xd4,
	0x80, 0x4c, 0x38, 0x1a, 0xa8, 0xc4, 0xe2, 0x13, 0xc3, 0x12, 0x48, 0x61, 0xab, 0x9e, 0x92, 0xf8,
	0x22, 0xa4, 0x5f, 0x01, 0xa2, 0x9e, 0x88, 0x0e, 0xe7, 0xf6, 0x5b, 0x15, 0x2b, 0xde, 0x4a, 0x13,
	0xa8, 0x05, 0x59, 0xb9, 0x55, 0xa9, 0xf7, 0x35, 0xa3, 0x15, 0x1a, 0x87, 0xcf, 0x3b, 0x70, 0xc4,
	0x5b, 0xf8, 0x42, 0xe9, 0x17, 0xa8, 0xb4, 0xa8, 0x4b, 0x19, 0x47, 0x73, 0x3c, 0x38, 0xe8, 0xef,
	0x93, 0xb0, 0x8a, 0x2a, 0x7d, 0xbc, 0xa0, 0x29, 0xa8, 0x59, 0xa2, 0x96, 0x55, 0x9c, 0xa0, 0xe9,
	0x16, 0x16, 0x87, 0xa9, 0xa8, 0xce, 0x01, 0x8a, 0x55, 0x94, 0x84, 0xc8, 0xdb, 0x59, 0x40, 0xf1,
	0x8a, 0x30, 0x95, 0xb7, 0x2a, 0x90, 0x09, 0x99, 0xf0, 0x35, 0xa9, 0x40, 0xf1, 0x47, 0x36, 0x5f,
	0xda, 0xf7, 0xda, 0xe5, 0x19, 0xec, 0xf7, 0xdd, 0x4a, 0x40, 0xfe, 0x09, 0xfa, 0x0e, 0xa9, 0xf0,
	0xb7, 0xe6, 0xdf, 0x0f, 0x48, 0x70, 0xdf, 0xf3, 0x86, 0xdd, 0x4b, 0xe0, 0xe1, 0xf2, 0x9b, 0x24,
	0x68, 0x69, 0xaf, 0x92, 0x70, 0xd7, 0xb0, 0xae, 0x6a, 0xf5, 0xdb, 0xe6, 0xd5, 0x5d, 0x27, 0xcd,
	0xfe, 0xe4, 0xfd, 0xf0, 0x31, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x42, 0x89, 0x7a, 0xf1, 0x0d, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	GetHostID(ctx context.Context, in *GetHostIDRequest, opts ...grpc.CallOption) (*GetHostIDReply, error)
	CreateThread(ctx context.Context, in *CreateThreadRequest, opts ...grpc.CallOption) (*ThreadInfoReply, error)
	AddThread(ctx context.Context, in *AddThreadRequest, opts ...grpc.CallOption) (*ThreadInfoReply, error)
	GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*ThreadInfoReply, error)
	PullThread(ctx context.Context, in *PullThreadRequest, opts ...grpc.CallOption) (*PullThreadReply, error)
	DeleteThread(ctx context.Context, in *DeleteThreadRequest, opts ...grpc.CallOption) (*DeleteThreadReply, error)
	AddReplicator(ctx context.Context, in *AddReplicatorRequest, opts ...grpc.CallOption) (*AddReplicatorReply, error)
	CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*NewRecordReply, error)
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordReply, error)
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordReply, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (API_SubscribeClient, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetHostID(ctx context.Context, in *GetHostIDRequest, opts ...grpc.CallOption) (*GetHostIDReply, error) {
	out := new(GetHostIDReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/GetHostID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateThread(ctx context.Context, in *CreateThreadRequest, opts ...grpc.CallOption) (*ThreadInfoReply, error) {
	out := new(ThreadInfoReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/CreateThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AddThread(ctx context.Context, in *AddThreadRequest, opts ...grpc.CallOption) (*ThreadInfoReply, error) {
	out := new(ThreadInfoReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/AddThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*ThreadInfoReply, error) {
	out := new(ThreadInfoReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/GetThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) PullThread(ctx context.Context, in *PullThreadRequest, opts ...grpc.CallOption) (*PullThreadReply, error) {
	out := new(PullThreadReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/PullThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteThread(ctx context.Context, in *DeleteThreadRequest, opts ...grpc.CallOption) (*DeleteThreadReply, error) {
	out := new(DeleteThreadReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/DeleteThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AddReplicator(ctx context.Context, in *AddReplicatorRequest, opts ...grpc.CallOption) (*AddReplicatorReply, error) {
	out := new(AddReplicatorReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/AddReplicator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*NewRecordReply, error) {
	out := new(NewRecordReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/CreateRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordReply, error) {
	out := new(AddRecordReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/AddRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordReply, error) {
	out := new(GetRecordReply)
	err := c.cc.Invoke(ctx, "/net.api.pb.API/GetRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (API_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/net.api.pb.API/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_SubscribeClient interface {
	Recv() (*NewRecordReply, error)
	grpc.ClientStream
}

type aPISubscribeClient struct {
	grpc.ClientStream
}

func (x *aPISubscribeClient) Recv() (*NewRecordReply, error) {
	m := new(NewRecordReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	GetHostID(context.Context, *GetHostIDRequest) (*GetHostIDReply, error)
	CreateThread(context.Context, *CreateThreadRequest) (*ThreadInfoReply, error)
	AddThread(context.Context, *AddThreadRequest) (*ThreadInfoReply, error)
	GetThread(context.Context, *GetThreadRequest) (*ThreadInfoReply, error)
	PullThread(context.Context, *PullThreadRequest) (*PullThreadReply, error)
	DeleteThread(context.Context, *DeleteThreadRequest) (*DeleteThreadReply, error)
	AddReplicator(context.Context, *AddReplicatorRequest) (*AddReplicatorReply, error)
	CreateRecord(context.Context, *CreateRecordRequest) (*NewRecordReply, error)
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordReply, error)
	GetRecord(context.Context, *GetRecordRequest) (*GetRecordReply, error)
	Subscribe(*SubscribeRequest, API_SubscribeServer) error
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) GetHostID(ctx context.Context, req *GetHostIDRequest) (*GetHostIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostID not implemented")
}
func (*UnimplementedAPIServer) CreateThread(ctx context.Context, req *CreateThreadRequest) (*ThreadInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateThread not implemented")
}
func (*UnimplementedAPIServer) AddThread(ctx context.Context, req *AddThreadRequest) (*ThreadInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddThread not implemented")
}
func (*UnimplementedAPIServer) GetThread(ctx context.Context, req *GetThreadRequest) (*ThreadInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThread not implemented")
}
func (*UnimplementedAPIServer) PullThread(ctx context.Context, req *PullThreadRequest) (*PullThreadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullThread not implemented")
}
func (*UnimplementedAPIServer) DeleteThread(ctx context.Context, req *DeleteThreadRequest) (*DeleteThreadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteThread not implemented")
}
func (*UnimplementedAPIServer) AddReplicator(ctx context.Context, req *AddReplicatorRequest) (*AddReplicatorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReplicator not implemented")
}
func (*UnimplementedAPIServer) CreateRecord(ctx context.Context, req *CreateRecordRequest) (*NewRecordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecord not implemented")
}
func (*UnimplementedAPIServer) AddRecord(ctx context.Context, req *AddRecordRequest) (*AddRecordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRecord not implemented")
}
func (*UnimplementedAPIServer) GetRecord(ctx context.Context, req *GetRecordRequest) (*GetRecordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (*UnimplementedAPIServer) Subscribe(req *SubscribeRequest, srv API_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetHostID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetHostID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/GetHostID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetHostID(ctx, req.(*GetHostIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/CreateThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateThread(ctx, req.(*CreateThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_AddThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AddThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/AddThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AddThread(ctx, req.(*AddThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/GetThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetThread(ctx, req.(*GetThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_PullThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).PullThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/PullThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).PullThread(ctx, req.(*PullThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/DeleteThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteThread(ctx, req.(*DeleteThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_AddReplicator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReplicatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AddReplicator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/AddReplicator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AddReplicator(ctx, req.(*AddReplicatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/CreateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateRecord(ctx, req.(*CreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/AddRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.api.pb.API/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).Subscribe(m, &aPISubscribeServer{stream})
}

type API_SubscribeServer interface {
	Send(*NewRecordReply) error
	grpc.ServerStream
}

type aPISubscribeServer struct {
	grpc.ServerStream
}

func (x *aPISubscribeServer) Send(m *NewRecordReply) error {
	return x.ServerStream.SendMsg(m)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "net.api.pb.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHostID",
			Handler:    _API_GetHostID_Handler,
		},
		{
			MethodName: "CreateThread",
			Handler:    _API_CreateThread_Handler,
		},
		{
			MethodName: "AddThread",
			Handler:    _API_AddThread_Handler,
		},
		{
			MethodName: "GetThread",
			Handler:    _API_GetThread_Handler,
		},
		{
			MethodName: "PullThread",
			Handler:    _API_PullThread_Handler,
		},
		{
			MethodName: "DeleteThread",
			Handler:    _API_DeleteThread_Handler,
		},
		{
			MethodName: "AddReplicator",
			Handler:    _API_AddReplicator_Handler,
		},
		{
			MethodName: "CreateRecord",
			Handler:    _API_CreateRecord_Handler,
		},
		{
			MethodName: "AddRecord",
			Handler:    _API_AddRecord_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _API_GetRecord_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _API_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
