// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: threads.proto

package threads_pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	pb "github.com/textileio/go-textile-core/crypto/pb"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RecordRequest struct {
	Node       []byte        `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	EventNode  []byte        `protobuf:"bytes,2,opt,name=event_node,json=eventNode,proto3" json:"event_node,omitempty"`
	HeaderNode []byte        `protobuf:"bytes,3,opt,name=header_node,json=headerNode,proto3" json:"header_node,omitempty"`
	BodyNode   []byte        `protobuf:"bytes,4,opt,name=body_node,json=bodyNode,proto3" json:"body_node,omitempty"`
	PublicKey  *pb.PublicKey `protobuf:"bytes,10,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature  []byte        `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *RecordRequest) Reset()         { *m = RecordRequest{} }
func (m *RecordRequest) String() string { return proto.CompactTextString(m) }
func (*RecordRequest) ProtoMessage()    {}
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ba358bb2150022, []int{0}
}
func (m *RecordRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RecordRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRequest.Merge(m, src)
}
func (m *RecordRequest) XXX_Size() int {
	return m.Size()
}
func (m *RecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRequest proto.InternalMessageInfo

func (m *RecordRequest) GetNode() []byte {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *RecordRequest) GetEventNode() []byte {
	if m != nil {
		return m.EventNode
	}
	return nil
}

func (m *RecordRequest) GetHeaderNode() []byte {
	if m != nil {
		return m.HeaderNode
	}
	return nil
}

func (m *RecordRequest) GetBodyNode() []byte {
	if m != nil {
		return m.BodyNode
	}
	return nil
}

func (m *RecordRequest) GetPublicKey() *pb.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *RecordRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RecordReply struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (m *RecordReply) Reset()         { *m = RecordReply{} }
func (m *RecordReply) String() string { return proto.CompactTextString(m) }
func (*RecordReply) ProtoMessage()    {}
func (*RecordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ba358bb2150022, []int{1}
}
func (m *RecordReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RecordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RecordReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RecordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordReply.Merge(m, src)
}
func (m *RecordReply) XXX_Size() int {
	return m.Size()
}
func (m *RecordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordReply.DiscardUnknown(m)
}

var xxx_messageInfo_RecordReply proto.InternalMessageInfo

func (m *RecordReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type LogInfo struct {
	Id         *ProtoPeerID   `protobuf:"bytes,1,opt,name=id,proto3,customtype=ProtoPeerID" json:"id,omitempty"`
	PublicKey  *pb.PublicKey  `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey *pb.PrivateKey `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	FollowKey  []byte         `protobuf:"bytes,4,opt,name=follow_key,json=followKey,proto3" json:"follow_key,omitempty"`
	ReadKey    []byte         `protobuf:"bytes,5,opt,name=read_key,json=readKey,proto3" json:"read_key,omitempty"`
	// The multiaddresses. This is a sorted list where element 0 expires the soonest.
	Addrs []*LogInfo_AddrEntry `protobuf:"bytes,6,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// The multiaddresses. This is a sorted list where element 0 expires the soonest.
	Heads []ProtoCid `protobuf:"bytes,7,rep,name=heads,proto3,customtype=ProtoCid" json:"heads,omitempty"`
}

func (m *LogInfo) Reset()         { *m = LogInfo{} }
func (m *LogInfo) String() string { return proto.CompactTextString(m) }
func (*LogInfo) ProtoMessage()    {}
func (*LogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ba358bb2150022, []int{2}
}
func (m *LogInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LogInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInfo.Merge(m, src)
}
func (m *LogInfo) XXX_Size() int {
	return m.Size()
}
func (m *LogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LogInfo proto.InternalMessageInfo

func (m *LogInfo) GetPublicKey() *pb.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *LogInfo) GetPrivateKey() *pb.PrivateKey {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *LogInfo) GetFollowKey() []byte {
	if m != nil {
		return m.FollowKey
	}
	return nil
}

func (m *LogInfo) GetReadKey() []byte {
	if m != nil {
		return m.ReadKey
	}
	return nil
}

func (m *LogInfo) GetAddrs() []*LogInfo_AddrEntry {
	if m != nil {
		return m.Addrs
	}
	return nil
}

// AddrEntry represents a single multiaddress.
type LogInfo_AddrEntry struct {
	Addr *ProtoAddr `protobuf:"bytes,1,opt,name=addr,proto3,customtype=ProtoAddr" json:"addr,omitempty"`
	// The point in time when this address expires.
	Expiry int64 `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// The original TTL of this address.
	Ttl int64 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (m *LogInfo_AddrEntry) Reset()         { *m = LogInfo_AddrEntry{} }
func (m *LogInfo_AddrEntry) String() string { return proto.CompactTextString(m) }
func (*LogInfo_AddrEntry) ProtoMessage()    {}
func (*LogInfo_AddrEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2ba358bb2150022, []int{2, 0}
}
func (m *LogInfo_AddrEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LogInfo_AddrEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LogInfo_AddrEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LogInfo_AddrEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInfo_AddrEntry.Merge(m, src)
}
func (m *LogInfo_AddrEntry) XXX_Size() int {
	return m.Size()
}
func (m *LogInfo_AddrEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInfo_AddrEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogInfo_AddrEntry proto.InternalMessageInfo

func (m *LogInfo_AddrEntry) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *LogInfo_AddrEntry) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func init() {
	proto.RegisterType((*RecordRequest)(nil), "threads.pb.RecordRequest")
	proto.RegisterType((*RecordReply)(nil), "threads.pb.RecordReply")
	proto.RegisterType((*LogInfo)(nil), "threads.pb.LogInfo")
	proto.RegisterType((*LogInfo_AddrEntry)(nil), "threads.pb.LogInfo.AddrEntry")
}

func init() { proto.RegisterFile("threads.proto", fileDescriptor_f2ba358bb2150022) }

var fileDescriptor_f2ba358bb2150022 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x8f, 0x12, 0x4d,
	0x10, 0xc6, 0x99, 0x19, 0x76, 0x61, 0x6a, 0xe0, 0x7d, 0x4d, 0xc7, 0x3f, 0x2c, 0xca, 0x80, 0x9c,
	0xb8, 0x30, 0x24, 0x90, 0x78, 0xd1, 0x8b, 0xa8, 0x31, 0x1b, 0x8d, 0x21, 0x1d, 0x0f, 0xde, 0x36,
	0x0c, 0xdd, 0xc0, 0x84, 0x91, 0x1e, 0x7b, 0x7a, 0xd6, 0x9d, 0xbb, 0x1f, 0xc0, 0x8f, 0xe4, 0xd1,
	0xe3, 0x26, 0x5e, 0x0c, 0x07, 0xa2, 0xf0, 0x25, 0x3c, 0x9a, 0xae, 0x06, 0x44, 0xe3, 0xc1, 0x5b,
	0x55, 0xfd, 0x9e, 0x27, 0xa9, 0x7a, 0xba, 0xa1, 0xaa, 0xe6, 0x92, 0x8f, 0x59, 0x1a, 0x24, 0x52,
	0x28, 0x41, 0xe0, 0xd0, 0x86, 0xf5, 0xee, 0x2c, 0x52, 0xf3, 0x2c, 0x0c, 0x26, 0xe2, 0x6d, 0x6f,
	0x26, 0x66, 0xa2, 0x87, 0x92, 0x30, 0x9b, 0x62, 0x87, 0x0d, 0x56, 0xc6, 0x5a, 0x7f, 0x78, 0x24,
	0x57, 0xfc, 0x4a, 0x45, 0x31, 0x8f, 0xb4, 0xa0, 0xbb, 0x6b, 0xba, 0x13, 0x21, 0x79, 0x6f, 0x22,
	0xf3, 0x44, 0x89, 0x5e, 0x12, 0xee, 0x2a, 0x63, 0x6e, 0x7f, 0xb1, 0xa0, 0x4a, 0xf9, 0x44, 0x48,
	0x46, 0xf9, 0xbb, 0x8c, 0xa7, 0x8a, 0x10, 0x28, 0x2e, 0x05, 0xe3, 0x35, 0xab, 0x65, 0x75, 0x2a,
	0x14, 0x6b, 0xd2, 0x00, 0xe0, 0x97, 0x7c, 0xa9, 0x2e, 0x90, 0xd8, 0x48, 0x5c, 0x9c, 0xbc, 0xd2,
	0xb8, 0x09, 0xde, 0x9c, 0x8f, 0x19, 0x97, 0x86, 0x3b, 0xc8, 0xc1, 0x8c, 0x50, 0x70, 0x17, 0xdc,
	0x50, 0xb0, 0xdc, 0xe0, 0x22, 0xe2, 0xb2, 0x1e, 0x20, 0x1c, 0x00, 0x24, 0x59, 0x18, 0x47, 0x93,
	0x8b, 0x05, 0xcf, 0x6b, 0xd0, 0xb2, 0x3a, 0x5e, 0xff, 0x66, 0xb0, 0xdf, 0x32, 0x0c, 0x46, 0x08,
	0x5f, 0xf0, 0x9c, 0xba, 0xc9, 0xbe, 0x24, 0xf7, 0xc0, 0x4d, 0xa3, 0xd9, 0x72, 0xac, 0x32, 0xc9,
	0x6b, 0x9e, 0x59, 0xe8, 0x30, 0x68, 0x37, 0xc0, 0xdb, 0x1f, 0x95, 0xc4, 0x39, 0xf9, 0x0f, 0x6c,
	0xb1, 0xc0, 0x83, 0xca, 0xd4, 0x16, 0x8b, 0xf6, 0x07, 0x07, 0x4a, 0x2f, 0xc5, 0xec, 0x7c, 0x39,
	0x15, 0xa4, 0x09, 0x76, 0xc4, 0xcc, 0xb1, 0xc3, 0xff, 0x57, 0xeb, 0xa6, 0x37, 0xd2, 0xb9, 0x8c,
	0x38, 0x97, 0xe7, 0x4f, 0xa9, 0x1d, 0xb1, 0x3f, 0xd6, 0xb3, 0xff, 0x6d, 0xbd, 0x07, 0xe0, 0x25,
	0x32, 0xba, 0x1c, 0x2b, 0x8e, 0x2e, 0x07, 0x5d, 0xb7, 0x8e, 0x5d, 0x86, 0x6a, 0x1b, 0x24, 0x87,
	0x5a, 0x07, 0x3d, 0x15, 0x71, 0x2c, 0xde, 0xa3, 0xcd, 0x24, 0xe5, 0x9a, 0x89, 0xc6, 0x67, 0x50,
	0xd6, 0xbf, 0x04, 0xe1, 0x09, 0xc2, 0x92, 0xee, 0x35, 0x1a, 0xc0, 0xc9, 0x98, 0x31, 0x99, 0xd6,
	0x4e, 0x5b, 0x4e, 0xc7, 0xeb, 0x37, 0x82, 0x5f, 0x1f, 0x2a, 0xd8, 0xdd, 0x1a, 0x3c, 0x66, 0x4c,
	0x3e, 0x5b, 0x2a, 0x99, 0x53, 0xa3, 0x25, 0x6d, 0x38, 0xd1, 0xaf, 0x94, 0xd6, 0x4a, 0x2d, 0xa7,
	0x53, 0x19, 0x56, 0x56, 0xeb, 0x66, 0x19, 0xef, 0x7f, 0x12, 0x31, 0x6a, 0x50, 0xfd, 0x0d, 0xb8,
	0x07, 0x1f, 0xb9, 0x0f, 0x45, 0xed, 0xdc, 0xe5, 0x55, 0x5d, 0xad, 0x9b, 0x2e, 0xea, 0xb5, 0x82,
	0x22, 0x22, 0xb7, 0xe1, 0x94, 0x5f, 0x25, 0x91, 0x34, 0x59, 0x39, 0x74, 0xd7, 0x91, 0x1b, 0xe0,
	0x28, 0x15, 0x63, 0x14, 0x0e, 0xd5, 0x65, 0xff, 0x39, 0x94, 0x5e, 0x9b, 0x25, 0xc9, 0x23, 0x28,
	0x8e, 0xb2, 0x74, 0x4e, 0xce, 0x8e, 0xd7, 0xfe, 0xed, 0x5f, 0xd6, 0xef, 0xfc, 0x0d, 0x25, 0x71,
	0xde, 0x2e, 0x0c, 0x5b, 0x3f, 0xbe, 0xfb, 0xd6, 0xa7, 0x8d, 0x6f, 0x7d, 0xde, 0xf8, 0xd6, 0xf5,
	0xc6, 0xb7, 0xbe, 0x6d, 0x7c, 0xeb, 0xe3, 0xd6, 0x2f, 0x5c, 0x6f, 0xfd, 0xc2, 0xd7, 0xad, 0x5f,
	0x08, 0x4f, 0xf1, 0xb7, 0x0f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x21, 0xf2, 0xad, 0x76,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ThreadsClient is the client API for Threads service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ThreadsClient interface {
	Push(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordReply, error)
}

type threadsClient struct {
	cc *grpc.ClientConn
}

func NewThreadsClient(cc *grpc.ClientConn) ThreadsClient {
	return &threadsClient{cc}
}

func (c *threadsClient) Push(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordReply, error) {
	out := new(RecordReply)
	err := c.cc.Invoke(ctx, "/threads.pb.Threads/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThreadsServer is the server API for Threads service.
type ThreadsServer interface {
	Push(context.Context, *RecordRequest) (*RecordReply, error)
}

func RegisterThreadsServer(s *grpc.Server, srv ThreadsServer) {
	s.RegisterService(&_Threads_serviceDesc, srv)
}

func _Threads_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreadsServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/threads.pb.Threads/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreadsServer).Push(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Threads_serviceDesc = grpc.ServiceDesc{
	ServiceName: "threads.pb.Threads",
	HandlerType: (*ThreadsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Threads_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "threads.proto",
}

func (m *RecordRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RecordRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Node) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThreads(dAtA, i, uint64(len(m.Node)))
		i += copy(dAtA[i:], m.Node)
	}
	if len(m.EventNode) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintThreads(dAtA, i, uint64(len(m.EventNode)))
		i += copy(dAtA[i:], m.EventNode)
	}
	if len(m.HeaderNode) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintThreads(dAtA, i, uint64(len(m.HeaderNode)))
		i += copy(dAtA[i:], m.HeaderNode)
	}
	if len(m.BodyNode) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintThreads(dAtA, i, uint64(len(m.BodyNode)))
		i += copy(dAtA[i:], m.BodyNode)
	}
	if m.PublicKey != nil {
		dAtA[i] = 0x52
		i++
		i = encodeVarintThreads(dAtA, i, uint64(m.PublicKey.Size()))
		n1, err := m.PublicKey.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Signature) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintThreads(dAtA, i, uint64(len(m.Signature)))
		i += copy(dAtA[i:], m.Signature)
	}
	return i, nil
}

func (m *RecordReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RecordReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Ok {
		dAtA[i] = 0x8
		i++
		if m.Ok {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *LogInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThreads(dAtA, i, uint64(m.Id.Size()))
		n2, err := m.Id.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.PublicKey != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintThreads(dAtA, i, uint64(m.PublicKey.Size()))
		n3, err := m.PublicKey.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.PrivateKey != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintThreads(dAtA, i, uint64(m.PrivateKey.Size()))
		n4, err := m.PrivateKey.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if len(m.FollowKey) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintThreads(dAtA, i, uint64(len(m.FollowKey)))
		i += copy(dAtA[i:], m.FollowKey)
	}
	if len(m.ReadKey) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintThreads(dAtA, i, uint64(len(m.ReadKey)))
		i += copy(dAtA[i:], m.ReadKey)
	}
	if len(m.Addrs) > 0 {
		for _, msg := range m.Addrs {
			dAtA[i] = 0x32
			i++
			i = encodeVarintThreads(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Heads) > 0 {
		for _, msg := range m.Heads {
			dAtA[i] = 0x3a
			i++
			i = encodeVarintThreads(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *LogInfo_AddrEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogInfo_AddrEntry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Addr != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThreads(dAtA, i, uint64(m.Addr.Size()))
		n5, err := m.Addr.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.Expiry != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintThreads(dAtA, i, uint64(m.Expiry))
	}
	if m.Ttl != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintThreads(dAtA, i, uint64(m.Ttl))
	}
	return i, nil
}

func encodeVarintThreads(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedRecordRequest(r randyThreads, easy bool) *RecordRequest {
	this := &RecordRequest{}
	v1 := r.Intn(100)
	this.Node = make([]byte, v1)
	for i := 0; i < v1; i++ {
		this.Node[i] = byte(r.Intn(256))
	}
	v2 := r.Intn(100)
	this.EventNode = make([]byte, v2)
	for i := 0; i < v2; i++ {
		this.EventNode[i] = byte(r.Intn(256))
	}
	v3 := r.Intn(100)
	this.HeaderNode = make([]byte, v3)
	for i := 0; i < v3; i++ {
		this.HeaderNode[i] = byte(r.Intn(256))
	}
	v4 := r.Intn(100)
	this.BodyNode = make([]byte, v4)
	for i := 0; i < v4; i++ {
		this.BodyNode[i] = byte(r.Intn(256))
	}
	if r.Intn(10) != 0 {
		this.PublicKey = pb.NewPopulatedPublicKey(r, easy)
	}
	v5 := r.Intn(100)
	this.Signature = make([]byte, v5)
	for i := 0; i < v5; i++ {
		this.Signature[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedRecordReply(r randyThreads, easy bool) *RecordReply {
	this := &RecordReply{}
	this.Ok = bool(bool(r.Intn(2) == 0))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedLogInfo(r randyThreads, easy bool) *LogInfo {
	this := &LogInfo{}
	this.Id = NewPopulatedProtoPeerID(r)
	if r.Intn(10) != 0 {
		this.PublicKey = pb.NewPopulatedPublicKey(r, easy)
	}
	if r.Intn(10) != 0 {
		this.PrivateKey = pb.NewPopulatedPrivateKey(r, easy)
	}
	v6 := r.Intn(100)
	this.FollowKey = make([]byte, v6)
	for i := 0; i < v6; i++ {
		this.FollowKey[i] = byte(r.Intn(256))
	}
	v7 := r.Intn(100)
	this.ReadKey = make([]byte, v7)
	for i := 0; i < v7; i++ {
		this.ReadKey[i] = byte(r.Intn(256))
	}
	if r.Intn(10) != 0 {
		v8 := r.Intn(5)
		this.Addrs = make([]*LogInfo_AddrEntry, v8)
		for i := 0; i < v8; i++ {
			this.Addrs[i] = NewPopulatedLogInfo_AddrEntry(r, easy)
		}
	}
	v9 := r.Intn(10)
	this.Heads = make([]ProtoCid, v9)
	for i := 0; i < v9; i++ {
		v10 := NewPopulatedProtoCid(r)
		this.Heads[i] = *v10
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedLogInfo_AddrEntry(r randyThreads, easy bool) *LogInfo_AddrEntry {
	this := &LogInfo_AddrEntry{}
	this.Addr = NewPopulatedProtoAddr(r)
	this.Expiry = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Expiry *= -1
	}
	this.Ttl = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Ttl *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyThreads interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneThreads(r randyThreads) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringThreads(r randyThreads) string {
	v11 := r.Intn(100)
	tmps := make([]rune, v11)
	for i := 0; i < v11; i++ {
		tmps[i] = randUTF8RuneThreads(r)
	}
	return string(tmps)
}
func randUnrecognizedThreads(r randyThreads, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldThreads(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldThreads(dAtA []byte, r randyThreads, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateThreads(dAtA, uint64(key))
		v12 := r.Int63()
		if r.Intn(2) == 0 {
			v12 *= -1
		}
		dAtA = encodeVarintPopulateThreads(dAtA, uint64(v12))
	case 1:
		dAtA = encodeVarintPopulateThreads(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateThreads(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateThreads(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateThreads(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateThreads(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *RecordRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Node)
	if l > 0 {
		n += 1 + l + sovThreads(uint64(l))
	}
	l = len(m.EventNode)
	if l > 0 {
		n += 1 + l + sovThreads(uint64(l))
	}
	l = len(m.HeaderNode)
	if l > 0 {
		n += 1 + l + sovThreads(uint64(l))
	}
	l = len(m.BodyNode)
	if l > 0 {
		n += 1 + l + sovThreads(uint64(l))
	}
	if m.PublicKey != nil {
		l = m.PublicKey.Size()
		n += 1 + l + sovThreads(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovThreads(uint64(l))
	}
	return n
}

func (m *RecordReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ok {
		n += 2
	}
	return n
}

func (m *LogInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != nil {
		l = m.Id.Size()
		n += 1 + l + sovThreads(uint64(l))
	}
	if m.PublicKey != nil {
		l = m.PublicKey.Size()
		n += 1 + l + sovThreads(uint64(l))
	}
	if m.PrivateKey != nil {
		l = m.PrivateKey.Size()
		n += 1 + l + sovThreads(uint64(l))
	}
	l = len(m.FollowKey)
	if l > 0 {
		n += 1 + l + sovThreads(uint64(l))
	}
	l = len(m.ReadKey)
	if l > 0 {
		n += 1 + l + sovThreads(uint64(l))
	}
	if len(m.Addrs) > 0 {
		for _, e := range m.Addrs {
			l = e.Size()
			n += 1 + l + sovThreads(uint64(l))
		}
	}
	if len(m.Heads) > 0 {
		for _, e := range m.Heads {
			l = e.Size()
			n += 1 + l + sovThreads(uint64(l))
		}
	}
	return n
}

func (m *LogInfo_AddrEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Addr != nil {
		l = m.Addr.Size()
		n += 1 + l + sovThreads(uint64(l))
	}
	if m.Expiry != 0 {
		n += 1 + sovThreads(uint64(m.Expiry))
	}
	if m.Ttl != 0 {
		n += 1 + sovThreads(uint64(m.Ttl))
	}
	return n
}

func sovThreads(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozThreads(x uint64) (n int) {
	return sovThreads(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RecordRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThreads
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RecordRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RecordRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Node = append(m.Node[:0], dAtA[iNdEx:postIndex]...)
			if m.Node == nil {
				m.Node = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventNode", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventNode = append(m.EventNode[:0], dAtA[iNdEx:postIndex]...)
			if m.EventNode == nil {
				m.EventNode = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeaderNode", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeaderNode = append(m.HeaderNode[:0], dAtA[iNdEx:postIndex]...)
			if m.HeaderNode == nil {
				m.HeaderNode = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BodyNode", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BodyNode = append(m.BodyNode[:0], dAtA[iNdEx:postIndex]...)
			if m.BodyNode == nil {
				m.BodyNode = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PublicKey == nil {
				m.PublicKey = &pb.PublicKey{}
			}
			if err := m.PublicKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThreads(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThreads
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthThreads
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RecordReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThreads
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RecordReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RecordReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ok", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Ok = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipThreads(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThreads
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthThreads
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LogInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThreads
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v ProtoPeerID
			m.Id = &v
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PublicKey == nil {
				m.PublicKey = &pb.PublicKey{}
			}
			if err := m.PublicKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrivateKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PrivateKey == nil {
				m.PrivateKey = &pb.PrivateKey{}
			}
			if err := m.PrivateKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FollowKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FollowKey = append(m.FollowKey[:0], dAtA[iNdEx:postIndex]...)
			if m.FollowKey == nil {
				m.FollowKey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReadKey = append(m.ReadKey[:0], dAtA[iNdEx:postIndex]...)
			if m.ReadKey == nil {
				m.ReadKey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addrs = append(m.Addrs, &LogInfo_AddrEntry{})
			if err := m.Addrs[len(m.Addrs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Heads", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v ProtoCid
			m.Heads = append(m.Heads, v)
			if err := m.Heads[len(m.Heads)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThreads(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThreads
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthThreads
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LogInfo_AddrEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThreads
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddrEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddrEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThreads
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthThreads
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v ProtoAddr
			m.Addr = &v
			if err := m.Addr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiry", wireType)
			}
			m.Expiry = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiry |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ttl", wireType)
			}
			m.Ttl = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ttl |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipThreads(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThreads
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthThreads
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipThreads(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowThreads
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowThreads
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthThreads
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthThreads
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowThreads
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipThreads(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthThreads
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthThreads = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowThreads   = fmt.Errorf("proto: integer overflow")
)
